name: Publish to PyPI

on:
  push:
    branches: [main]
#  release:
#    types: [published]

permissions:
  contents: read

jobs:
  main:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: Install latest pip and build
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build
      - name: Build source distribution & pure wheel
        run: python -m build

      - name: Upload sdist as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/

#  cibuildwheel:
#    name: Build wheels on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-20.04, windows-2019, macos-11]
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Build wheels
#        uses: pypa/cibuildwheel@v2.10.2
#
#      - name: Upload wheels as workflow artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          path: ./wheelhouse/*.whl

  upload_all:
    name: Upload to PyPI
    needs: [main]  # cibuildwheel
    runs-on: ubuntu-latest

    steps:
      - name: Download workflow artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Upload to PyPI via Twine
#        if: github.event_name == "push" && startsWith(github.ref, "refs/tags")
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
# for live publishing: remove the following two lines, uncomment the `if` above, and update PYPI_TOKEN
          repository_url: https://test.pypi.org/legacy/
          verbose: true
